### ISSUE TITLE
Prod build post get 404

### ISSUE THREAD

**Issue by yaozhongjing2020** [techhiveIO/nextjs-static-starter-kit#6]
## Minimal reproduction of the bug with instructions:
npm run build && npm run start
reload one of the post page

## Expected behavior:
should see the post page with blog

## Other information:
Instead it has 404 page for the innner container

## I would be willing to submit a PR to fix this issue:

[X] Yes (Assistance is provided if you need help submitting a pull request)  
[ ] No

**Comment by abedzantout** [comment]
Hello!

This was fixed in the latest release. Please let us know if you still have the problem

**Comment by abedzantout** [comment]
Closing this PR for now. Will re-open if the problem persists.
