### ISSUE TITLE
cannot get DOMAIN_NAME when building the sitemap

### ISSUE THREAD

**Issue by yaozhongjing2020** [techhiveIO/nextjs-static-starter-kit#7]
## Minimal reproduction of the bug with instructions:
```npm  run export```

## Expected behavior:
Should be able to run successfully

## Other information:
Instead because it is not in a node env run time, env is undefined so that not able to use the DOMAIN_NAME variable in the .env file

## I would be willing to submit a PR to fix this issue:

[X] Yes (Assistance is provided if you need help submitting a pull request)  
[ ] No

**Comment by abedzantout** [comment]
Can you please provide us with additional details?

Also, feel free to submit a PR if you found the solution

**Comment by abedzantout** [comment]
Closing this PR for now. Will re-open if the problem persists.
